# This is a basic workflow to help you get started with Actions
 
name:
  First Cron Job
 
  # Controls when the workflow will run
on:
  # Triggers the workflow every day at 11:00 UTC
  schedule:
    - cron: "0 11 * * *"
 
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run python script
        run: python3 update_number.py